name: Generate

on:
  push:
    paths:
      - app.py

jobs:
  genearte:
    runs-on: ubuntu-latest
    name: Generate Video
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run scripts
        env:
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
        run: python app.py
      - name: Save Video to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: video-results
          path: results/*
